### ISSUE TITLE
Rollback Error

### ISSUE THREAD

**Issue by anchalmarwah** [amazon-connect/amazon-connect-call-quality-monitoring#15]
Hi all,

I am trying to use the stack to get the AWS monitoring working from the below repos:
serverlessrepo-AmazonConnectMonitoringSolution

I am getting to the last file and then its rolling back due to this:
CodeBuildTriggerInvoke	-	AWS::CloudFormation::CustomResource	CREATE_IN_PROGRESS ---Fails and then 

serverlessrepo-AmazonConnectMonitoringSolution-Rolls back, by deleting every other thing.

Any idea why is it behaving that please?
Any one else having these problems?

Thanks,
Anchal

**Comment by anchalmarwah** [comment]
As the solution is not getting deployed, I dont get a Cloudfront URL, a Cognito URL as well, in SSM.

**Comment by angieyu** [comment]
Can you please try deploying with this link? https://serverlessrepo.aws.amazon.com/applications/us-west-2/287087860234/AmazonConnectMonitoringSolution

There is an orange "deploy" button on the top right hand corner.

**Comment by anchalmarwah** [comment]
Hello Angela,

Thank you for your email.

I have already tried that link earlier, which is failing. Is this a
different link to the one provided in my query?

Thanks,

**Comment by mcosicaws** [comment]
Could you please provide more details from CloudFormation console? There should be an error message, describing a root cause for the rollback. Please note that there might be multiple 'error' messages, basically, one would be the root cause, and the other error(s) would be a consequence of 'cancelling' resource creation during the rollback.

**Comment by khastation** [comment]
@anchalmarwah Please reopen this issue if you continue to face this issue with detailed error messages.

**Comment by Kannan2022** [comment]
even im facing same issue 

<html>
<body>


CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [2f83d1e3-58e2-4eb5-803e-bfa7cb216805]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by SadhanaVanvi** [comment]
Is there any solution to this Error
I am also getting the same error as above 
Please provide any resolution.
