### ISSUE TITLE
Deployment failing at CodeBuildTriggerInvoke	

### ISSUE THREAD

**Issue by gturn27** [amazon-connect/amazon-connect-call-quality-monitoring#3]
When I follow the instructions given for deployment, the CloudFormation is getting stuck at CodeBuildTriggerInvoke.  After about an hour, the CodeBuildTriggerInvoke fails giving the reason of 'Custom Resource failed to stabilize in expected time', and then the deployment rolls back.  

I tried the deployment 3 times, and had the same result each time.  Any idea what could be causing this problem?

**Comment by efh365** [comment]
Hi @gturn27, can you please look at the CloudWatch Logs generated by the CodeBuildTriggerInvoke function? That will have more details as to why it is failing.

**Comment by gturn27** [comment]
Thanks, I checked CloudWatch, but there aren't any logs for the CodeBuildTriggerInvoke function.  I do see this error in the CDKBuilder log when it tries to bootstrap (I removed my account ID)-   "Environment aws://xxxxxx/us-east-1 failed bootstrapping: Error: Not downgrading existing bootstrap stack from version '4' to version '0'. Use --force to force"

**Comment by kqia040** [comment]
Hey @gturn27 I've been able to reproduce this in accounts where cdk bootstrap has already been run in the region (with a different version of cdk). We're working on a update to the deployment mechanism, should be released by the end of the month.

**Comment by kqia040** [comment]
Meanwhile, as a workaround you can clone this repository and cdk deploy the monitoring-stack-cdk app locally.

**Comment by taylor-zr** [comment]
Hello @gturn27! We've deployed a solution that resolves this issue. Please give it a go and let us know if you run into any issues.

**Comment by gturn27** [comment]
I ran the deployment today and it worked.  Thanks!

**Comment by SadhanaVanvi** [comment]
Hi 
I am also facing the same issue with CodeBuildTriggerInvoke as it is getting failed and deployment rolls back.
it says error in Cloudformation stack events :
"CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [xxxx-xxxx-xxxx-xxxx]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version."
and Cloudwatch Error :
[Container]  Phase complete: INSTALL State: FAILED
[Container] Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk --version. Reason: exit status 1

Could you  please suggest something on this how to resolve this error.

Thanks,
Sadhana
